Bangladesh = {
    "Dhaka": {
        "Dhaka": ["Adabar", "Azampur", "Badda", "Bangsal", "Bimanbandar", "Cantonment", "Chak Bazar", "Darus Salam", "Demra", "Dhamrai", "Dhanmondi",
                  "Dohar", "Gandaria", "Gulshan", "Hazaribagh", "Jatrabari", "Kafrul", "Kalabagan", "Kamrangirchar", "Keraniganj", "Khilgaon", "Khilkhet",
                  "Kotwali", "Lalbagh", "Mirpur", "Mohammadpur", "Motijheel", "Nawabganj", "New Market", "Pallabi", "Paltan", "Ramna", "Rampura", "Sabujbagh",
                  "Shah Ali", "Shahbagh", "Sher-e-Bangla Nagar", "Shyampur", "Sutrapur", "Tejgaon", "Tejgaon Industrial Area", "Turag", "Uttar Khan", "Uttara"],
        "Gazipur": ["Amin Bazar", "Amin Bazar Cadet College", "Ashulia", "B.O.F", "Baipail", "Bhawal Badre Alam Govt. College", "Bhawal Rajabari", "Chandra",
                    "D.C Road", "Dhamrai", "EPZ", "Gazipur Sadar", "H.R Textile School & College", "Joydebpur", "Kaliakair", "Kaliganj", "Kaliganj (Bosti)",
                    "Kashimpur", "Kashor", "Kawraid", "Mirzapur", "National University", "Nishat Nagar", "Nobinagar", "Pachdona", "Pubail", "Rajendrapur",
                    "Sataish", "Tongi (Nagor)", "Tongi Govt. College", "Vaoal Jamalpur"],
        "Narayanganj": ["Araihazar", "Bandar", "BND College", "D.C Mills", "Fatullah", "Gauripur", "Kadam Rasul", "Kanchpur", "Kashipur",
                        "Narayanganj Sadar", "NITA", "Rupganj", "Siddirganj"],
        "Tangail": ["Bhuapur", "Delduar", "Ghatail", "Gopalpur", "Kalihati", "Madhupur", "Mirzapur", "Nagarpur", "Sakhipur", "Tangail Sadar"],
        "Mymensingh": ["Bhaluka", "Dhobaura", "Fulbaria", "Gaffargaon", "Gauripur", "Haluaghat", "Ishwarganj", "Muktagacha", "Mymensingh Sadar",
                       "Nandail", "Phulpur", "Trishal"],
        "Jamalpur": ["Bakshiganj", "Dewanganj", "Islampur", "Jamalpur Sadar", "Madarganj", "Melandaha", "Sarishabari"],
        "Manikganj": ["Doulatpur", "Gheor", "Harirampur", "Manikganj Sadar", "Saturia", "Shibalaya", "Singair"],
        "Narsingdi": ["Belabo", "Monohardi", "Narsingdi Sadar", "Palash", "Raipura", "Shibpur"],
        "Sherpur": ["Jhenaigati", "Nakla", "Nalitabari", "Sherpur Sadar", "Sreebardi"],
        "Rajbari": ["Baliakandi", "Goalandaghat", "Pangsha", "Rajbari Sadar"],
        "Kishoreganj": ["Austagram", "Bajitpur", "Bhairab", "Hossainpur", "Itna", "Karimganj", "Katiadi", "Kishoreganj Sadar", "Kuliarchar",
                        "Mithamain", "Nikli", "Pakundia", "Tarail"],
        "Faridpur": ["Alfadanga", "Bhanga", "Boalmari", "Charbhadrasan", "Faridpur Sadar", "Madhukhali", "Nagarkanda", "Sadarpur", "Saltha"],
        "Madaripur": ["Kalkini", "Madaripur Sadar", "Rajoir", "Shibchar"],
        "Gopalganj": ["Gopalganj Sadar", "Kashiani", "Kotalipara", "Muksudpur", "Tungipara"],
        "Munshiganj": ["Gazaria", "Lohajang", "Munshiganj Sadar", "Sirajdikhan", "Sreenagar", "Tongibari"],
    },
    "Chittagong": {
        "Chittagong": ["Anwara", "Banshkhali", "Boalkhali", "Chandanaish", "Chandgaon", "Double Mooring", "Fatikchhari", "Hathazari", "Karnaphuli",
                       "Kotwali", "Lohagara", "Mirsharai", "Pahartali", "Panchlaish", "Patiya", "Rangunia", "Raozan", "Sandwip", "Satkania", "Sitakunda"],
        "Cox's Bazar": ["Cox's Bazar Sadar", "Kutubdia", "Ramu", "Chakaria", "Ukhia", "Teknaf", "Maheshkhali"],
        "Khagrachari": ["Khagrachari Sadar", "Dighinala", "Mahalchhari", "Manikchhari", "Matiranga", "Panchhari", "Ramgarh"],
        "Rangamati": ["Rangamati Sadar", "Bagaichhari", "Barkal", "Juraichhari", "Kaptai", "Langadu", "Naniarchar", "Rajasthali"],
        "Bandarban": ["Bandarban Sadar", "Thanchi", "Ruma", "Rowangchhari"],
        "Feni": ["Feni Sadar", "Chagalnaiya", "Daganbhuiyan", "Parshuram", "Fulgazi", "Sonagazi"],
        "Lakshmipur": ["Lakshmipur Sadar", "Raipur", "Ramganj", "Ramgati", "Komol Nagar"],
        "Comilla": ["Comilla Sadar", "Barura", "Brahmanpara", "Burichang", "Chandina", "Chauddagram", "Daudkandi", "Debidwar", "Homna", "Laksam",
                    "Manoharganj", "Meghna", "Muradnagar", "Nangalkot", "Titas"],
        "Noakhali": ["Noakhali Sadar", "Basurhat", "Begumganj", "Chatkhil", "Companiganj", "Hatiya", "Senbagh", "Sonaimuri", "Subarnachar"],
        "Brahmanbaria": ["Brahmanbaria Sadar", "Ashuganj", "Bancharampur", "Bijoynagar", "Kasba", "Nabinagar", "Nasirnagar", "Sarail", "Shahbazpur"],
        "Chandpur": ["Chandpur Sadar", "Faridganj", "Haimchar", "Haziganj", "Kachua", "Matlab Dakshin", "Matlab Uttar", "Shahrasti"],
    },
    "Rajshahi": {
        "Rajshahi": ["Rajshahi Sadar", "Bagha", "Bagmara", "Boalia", "Charghat", "Durgapur", "Godagari", "Mohanpur", "Paba", "Puthia", "Tanore"],
        "Naogaon": ["Naogaon Sadar", "Atrai", "Badalgachhi", "Dhamoirhat", "Manda", "Mohanpur", "Niamatpur", "Patnitala", "Porsha", "Raninagar", "Sapahar"],
        "Natore": ["Natore Sadar", "Baraigram", "Bagatipara", "Gurudaspur", "Lalpur", "Singra"],
        "Chapainawabganj": ["Chapainawabganj Sadar", "Bholahat", "Gomastapur", "Nachole", "Shibganj"],
        "Pabna": ["Pabna Sadar", "Atgharia", "Bera", "Bhangura", "Chatmohar", "Faridpur", "Ishwardi", "Santhia", "Sujanagar"],
        "Sirajganj": ["Sirajganj Sadar", "Belkuchi", "Chauhali", "Kamarkhanda", "Kazipur", "Raiganj", "Shahjadpur", "Tarash", "Ullahpara"],
    },
    "Khulna": {
        "Khulna": ["Khulna Sadar", "Batiaghata", "Dacope", "Dumuria", "Dighalia", "Khalishpur", "Koyra", "Paikgachha", "Phultala", "Rupsa", "Terokhada"],
        "Bagerhat": ["Bagerhat Sadar", "Chitalmari", "Fakirhat", "Kachua", "Mollahat", "Mongla", "Morrelganj", "Rampal", "Sarankhola"],
        "Chuadanga": ["Chuadanga Sadar", "Alamdanga", "Damurhuda", "Jibannagar"],
        "Jessore": ["Jessore Sadar", "Abhaynagar", "Bagherpara", "Chaugachha", "Jhikargachha", "Keshabpur", "Manirampur", "Sharsha"],
        "Jhenaidah": ["Jhenaidah Sadar", "Harinakunda", "Kaliganj", "Kotchandpur", "Maheshpur", "Shailkupa"],
        "Kushtia": ["Kushtia Sadar", "Bheramara", "Daulatpur", "Khoksa", "Kumarkhali", "Mirpur"],
        "Magura": ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
        "Meherpur": ["Meherpur Sadar", "Gangni", "Mujib Nagar"],
        "Narail": ["Narail Sadar", "Lohagara", "Kalia"],
        "Satkhira": ["Satkhira Sadar", "Assasuni", "Debhata", "Kalaroa", "Kaliganj", "Shyamnagar", "Tala"],
    },
    "Barisal": {
        "Barisal": ["Barisal Sadar", "Agailjhara", "Babuganj", "Bakerganj", "Banaripara", "Gaurnadi", "Hizla", "Mehendiganj", "Muladi", "Wazirpur"],
        "Barguna": ["Barguna Sadar", "Amtali", "Bamna", "Betagi", "Patharghata", "Taltali"],
        "Bhola": ["Bhola Sadar", "Borhanuddin", "Char Fasson", "Doulatkhan", "Lalmohan", "Manpura", "Tazumuddin"],
        "Jhalokati": ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
        "Patuakhali": ["Patuakhali Sadar", "Bauphal", "Dashmina", "Dumki", "Galachipa", "Kala Para", "Mirzaganj", "Rangabali"],
        "Pirojpur": ["Pirojpur Sadar", "Bhandaria", "Kaukhali", "Mathbaria", "Nazirpur", "Nesarabad", "Zianagar"],
    },
    "Sylhet": {
        "Habiganj": ["Habiganj Sadar", "Ajmiriganj", "Baniachong", "Bahubal", "Chunarughat", "Lakhai", "Madhabpur", "Nabiganj"],
        "Moulvibazar": ["Moulvibazar Sadar", "Barlekha", "Juri", "Kamalganj", "Kulaura", "Rajnagar", "Sreemangal"],
        "Sunamganj": ["Sunamganj Sadar", "Bishwamvarpur", "Chhatak", "Dharamapasha", "Dowarabazar", "Jamalganj", "Shanthiganj", "Tahirpur"],
        "Sylhet": ["Sylhet Sadar", "Balaganj", "Beanibazar", "Bishwanath", "Fenchuganj", "Golapganj", "Gowainghat", "Jaintiapur", "Kanaighat", "Zakiganj"],
    },
    "Rangpur": {
        "Dinajpur": ["Birampur", "Birganj", "Bochaganj", "Chirirbandar", "Dinajpur Sadar", "Fulbari", "Ghoraghat", "Hakimpur", "Kaharole", "Khansama", "Nawabganj", "Parbatipur"],
        "Gaibandha": ["Fulchhari", "Gaibandha Sadar", "Gobindaganj", "Palashbari", "Sadullapur", "Sughatta", "Sundarganj"],
        "Kurigram": ["Bhurungamari", "Char Rajibpur", "Chilmari", "Kurigram Sadar", "Nageshwari", "Phulbari", "Rajarhat", "Rowmari", "Ulipur"],
        "Lalmonirhat": ["Aditmari", "Hatibandha", "Kaliganj", "Lalmonirhat Sadar", "Patgram"],
        "Nilphamari": ["Dimla", "Domar", "Jaldhaka", "Kishoreganj", "Nilphamari Sadar", "Saidpur"],
        "Panchagarh": ["Atwari", "Boda", "Debiganj", "Panchagarh Sadar", "Tetulia"],
        "Rangpur": ["Badarganj", "Gangachara", "Kaunia", "Pirgachha", "Rangpur Sadar", "Mithapukur", "Pirganj", "Taraganj"],
        "Thakurgaon": ["Baliadangi", "Haripur", "Ranisankail", "Thakurgaon Sadar"],
    },
    "Mymensingh": {
        "Jamalpur": ["Bakshiganj", "Dewanganj", "Islampur", "Jamalpur Sadar", "Madarganj", "Melandaha", "Sarishabari"],
        "Mymensingh": ["Bhaluka", "Dhobaura", "Fulbaria", "Gaffargaon", "Gauripur", "Haluaghat", "Ishwarganj", "Muktagachha", "Mymensingh Sadar", "Nandail", "Phulpur", "Trishal"],
        "Netrokona": ["Atpara", "Barhatta", "Durgapur", "Kalmakanda", "Kendua", "Khaliajuri", "Madan", "Mohanganj", "Netrokona Sadar", "Purbadhala"],
        "Sherpur": ["Jhenaigati", "Nakla", "Nalitabari", "Sherpur Sadar", "Sreebardi"],
    },
}