# Generated by Django 4.2.3 on 2023-09-06 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.PositiveIntegerField(default=1, null=True)),
                ('code', models.CharField(max_length=4, null=True)),
                ('variants', models.CharField(choices=[('Whole Fish', 'Whole Fish'), ('Half', 'Half'), ('One Third', 'One Third'), ('Quarter', 'Quarter'), ('NA', 'NA')], max_length=15, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('probable_weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=11, null=True, unique=True)),
                ('password', models.CharField(max_length=14, null=True)),
                ('fullName', models.CharField(max_length=31, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Common', 'Common')], max_length=6, null=True)),
                ('division', models.CharField(max_length=31, null=True)),
                ('district', models.CharField(max_length=31, null=True)),
                ('thana', models.CharField(max_length=31, null=True)),
                ('union', models.CharField(blank=True, max_length=31, null=True)),
                ('village', models.CharField(max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='customer_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customer_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, null=True, unique=True)),
                ('name', models.CharField(max_length=63, null=True)),
                ('bangla_name', models.CharField(max_length=63, null=True)),
                ('size', models.CharField(choices=[('XS', 'Extra_small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra_large'), ('XXL', 'Ultra_large')], max_length=14, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('love', models.BooleanField(default=False, null=True)),
                ('add_to_cart', models.BooleanField(default=False, null=True)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=2, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('probable_weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('availability', models.BooleanField(default=True, null=True)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('category', models.CharField(choices=[('Sea Fish', 'Sea Fish'), ('River Fish', 'River Fish'), ('Pond Fish', 'Pond Fish'), ('Bill Fish', 'Bill Fish'), ('other', 'Other')], max_length=28, null=True)),
                ('supplier', models.CharField(max_length=54, null=True)),
                ('variants', models.CharField(choices=[('Whole Fish', 'Whole Fish'), ('Half', 'Half'), ('One Third', 'One Third'), ('Quarter', 'Quarter'), ('NA', 'NA')], default='NA', max_length=15, null=True)),
                ('types', models.CharField(choices=[('Dry', 'Dry'), ('Soft', 'Soft')], default='Soft', max_length=15, null=True)),
                ('reviews', models.TextField(default='Rated By @Author', null=True)),
                ('ratings', models.DecimalField(decimal_places=2, default='5', max_digits=3, null=True)),
                ('shipping', models.TextField(default='NA', max_length=14, null=True)),
                ('in_stock', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('payment_method', models.CharField(choices=[('Cash on Deilivery', 'cod'), ('bKash', 'bkash'), ('Nagad', 'nagad'), ('DBBL', 'dbbl'), ('Other', 'other')], default='bKash', max_length=28, null=True)),
                ('details', models.TextField(default='NA', max_length=512, null=True)),
                ('videos', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('SN', models.IntegerField()),
                ('Name', models.CharField(max_length=127)),
                ('Image', models.URLField()),
                ('Weight', models.CharField(max_length=14)),
                ('Price', models.CharField(max_length=14)),
                ('Quantity', models.IntegerField()),
                ('Discount', models.CharField(max_length=14)),
                ('Total', models.CharField(default='', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=11)),
                ('trxid', models.CharField(default='', max_length=31, unique=True)),
                ('paidFrom', models.CharField(default='', max_length=31)),
                ('Paid', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('division', models.CharField(blank=True, max_length=31, null=True)),
                ('district', models.CharField(blank=True, max_length=31, null=True)),
                ('thana', models.CharField(blank=True, max_length=31, null=True)),
                ('paymentMethod', models.CharField(blank=True, max_length=31, null=True)),
                ('username', models.CharField(max_length=11)),
                ('fullName', models.CharField(blank=True, max_length=31, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('union', models.CharField(blank=True, max_length=31, null=True)),
                ('village', models.TextField(blank=True, max_length=255, null=True)),
                ('altMobileNo', models.CharField(blank=True, max_length=11, null=True)),
                ('trxid', models.CharField(blank=True, max_length=63, null=True)),
                ('GrandTotal', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('Paid', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('Due', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('Transaction', models.ManyToManyField(blank=True, to='cheradip.transaction')),
                ('orderDetails', models.ManyToManyField(blank=True, to='cheradip.orderdetail')),
            ],
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('division', models.CharField(blank=True, max_length=31, null=True)),
                ('district', models.CharField(blank=True, max_length=31, null=True)),
                ('thana', models.CharField(blank=True, max_length=31, null=True)),
                ('paymentMethod', models.CharField(blank=True, max_length=31, null=True)),
                ('username', models.CharField(max_length=11)),
                ('fullName', models.CharField(blank=True, max_length=31, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('union', models.CharField(blank=True, max_length=31, null=True)),
                ('village', models.TextField(blank=True, max_length=255, null=True)),
                ('altMobileNo', models.CharField(blank=True, max_length=11, null=True)),
                ('trxid', models.CharField(blank=True, max_length=63, null=True)),
                ('GrandTotal', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('Paid', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('Due', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('Transaction', models.ManyToManyField(blank=True, to='cheradip.transaction')),
                ('orderDetails', models.ManyToManyField(blank=True, to='cheradip.orderdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cheradip.customer')),
            ],
        ),
    ]
