# Generated by Django 4.2.3 on 2023-09-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neworder',
            name='Due',
        ),
        migrations.RemoveField(
            model_name='neworder',
            name='GrandTotal',
        ),
        migrations.RemoveField(
            model_name='neworder',
            name='Paid',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='Due',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='GrandTotal',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='Paid',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Discount',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Total',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
