# Generated by Django 4.2.3 on 2023-09-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0002_remove_neworder_due_remove_neworder_grandtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neworder',
            name='trxid',
        ),
    ]
