# Generated by Django 4.2.3 on 2023-09-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0003_remove_neworder_trxid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neworder',
            old_name='Transaction',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Transaction',
            new_name='transaction',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Due',
        ),
        migrations.RemoveField(
            model_name='order',
            name='GrandTotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='trxid',
        ),
    ]
