# Generated by Django 4.2.3 on 2023-09-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0005_alter_cart_customer_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='ShipingCost',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
    ]
