# Generated by Django 5.0.2 on 2025-04-08 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Experience',
        ),
    ]
