# Generated by Django 5.0.2 on 2025-04-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Retirement',
        ),
        migrations.RemoveField(
            model_name='teacherhonours',
            name='Retirement',
        ),
    ]
