# Generated by Django 4.1.13 on 2025-04-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Retirement',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Retirement',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='nonmpostaff',
            name='Retirement',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='otherpeople',
            name='Retirement',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Retirement',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Retirement',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Retirement',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='teacherpart',
            name='Retirement',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
