# Generated by Django 4.1.13 on 2025-04-20 01:16

from django.db import migrations, models
import django.db.models.deletion
import kbm.models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatedimage',
            old_name='caption',
            new_name='Caption',
        ),
    ]
