# Generated by Django 5.0.2 on 2024-02-26 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(blank=True, max_length=62, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Common', 'Common')], max_length=6, null=True)),
                ('fathersName', models.CharField(blank=True, max_length=62, null=True)),
                ('mothersName', models.CharField(blank=True, max_length=62, null=True)),
                ('husband', models.CharField(blank=True, max_length=62, null=True)),
                ('designation', models.CharField(blank=True, max_length=62, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('index', models.CharField(blank=True, max_length=14, null=True)),
                ('joiningDate', models.DateTimeField(blank=True, null=True)),
                ('bankAccount', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('tors', models.BooleanField(blank=True, default=False, null=True)),
                ('morh', models.BooleanField(blank=True, default=False, null=True)),
                ('password', models.CharField(blank=True, max_length=14, null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=14, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('comments', models.TextField(blank=True, max_length=510, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(blank=True, max_length=30, null=True)),
                ('thana', models.CharField(blank=True, max_length=30, null=True)),
                ('union', models.CharField(blank=True, max_length=30, null=True)),
                ('postCode', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('village', models.CharField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(blank=True, max_length=62, null=True)),
                ('institute', models.CharField(blank=True, max_length=254, null=True)),
                ('passingYear', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('maxGrade', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('pClass', models.CharField(blank=True, max_length=62, null=True)),
                ('boardUniversity', models.CharField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pInstitute', models.CharField(blank=True, max_length=126, null=True)),
                ('pijd', models.DateTimeField(blank=True, null=True)),
                ('pird', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
