# Generated by Django 4.1.13 on 2025-04-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0002_alter_departments_id_alter_exstaff_retirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='TitleStaff',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='TitleTeacher',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='TitleTeacherHonours',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='TitleTeacherPart',
        ),
        migrations.AddField(
            model_name='departments',
            name='DescriptionPhoto',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='relatedimage',
            name='image',
            field=models.ImageField(upload_to='images/depts'),
        ),
    ]
