# Generated by Django 4.1.13 on 2025-04-20 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kbm.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kbm', '0002_rename_caption_relatedimage_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='Users',
            field=models.ManyToManyField(blank=True, related_name='depts', to=settings.AUTH_USER_MODEL),
        ),
    ]
