# Generated by Django 5.0.2 on 2025-04-08 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0002_remove_teacher_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exstaff',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='exteacher',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='nonmpostaff',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='teacherhonours',
            name='Experience',
        ),
        migrations.AddField(
            model_name='education',
            name='ExStaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='kbm.exstaff'),
        ),
        migrations.AddField(
            model_name='education',
            name='ExTeacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='kbm.exteacher'),
        ),
        migrations.AddField(
            model_name='education',
            name='NonMpoStaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='kbm.nonmpostaff'),
        ),
        migrations.AddField(
            model_name='education',
            name='OtherPeople',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='kbm.otherpeople'),
        ),
        migrations.AddField(
            model_name='education',
            name='Staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='kbm.staff'),
        ),
        migrations.AddField(
            model_name='education',
            name='TeacherHonours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='kbm.teacherhonours'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Retirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherhonours',
            name='Retirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='kbm.teacher'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=63, null=True)),
                ('Year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('Description', models.CharField(blank=True, max_length=1024, null=True)),
                ('Comment', models.CharField(blank=True, max_length=255, null=True)),
                ('ExStaff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='kbm.exstaff')),
                ('ExTeacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='kbm.exteacher')),
                ('NonMpoStaff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='kbm.nonmpostaff')),
                ('OtherPeople', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='kbm.otherpeople')),
                ('Staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='kbm.staff')),
                ('Teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='kbm.teacher')),
                ('TeacherHonours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='kbm.teacherhonours')),
            ],
        ),
    ]
