# Generated by Django 4.1.13 on 2025-04-20 01:38

from django.db import migrations, models
import django.db.models.deletion
import kbm.models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0003_remove_relatedimage_image_dept_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='Users',
        ),
        migrations.RemoveField(
            model_name='relatedimage',
            name='image',
        ),
        migrations.AddField(
            model_name='relatedimage',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to=kbm.models.upload_to_dept_folder),
        ),
        migrations.AlterField(
            model_name='dept',
            name='Name',
            field=models.CharField(default='Administration', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='kbm.dept')),
            ],
        ),
    ]
