# Generated by Django 5.0.2 on 2025-04-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0003_alter_exstaff_dob_alter_exstaff_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exstaff',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Degree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Degree_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Degree_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Degree_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='HSC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='HSC_Board',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='HSC_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='HSC_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Honours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Honours_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Honours_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Honours_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Masters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Masters_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Masters_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Masters_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='PerAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='PreAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='PreMasters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='PreMasters_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='PreMasters_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='PreMasters_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='Retirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='SSC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='SSC_Board',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='SSC_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exstaff',
            name='SSC_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Degree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Degree_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Degree_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Degree_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='HSC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='HSC_Board',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='HSC_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='HSC_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Honours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Honours_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Honours_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Honours_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Masters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Masters_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Masters_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Masters_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='PerAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='PreAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='PreMasters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='PreMasters_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='PreMasters_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='PreMasters_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Retirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='SSC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='SSC_Board',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='SSC_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='SSC_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherpeople',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherpeople',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otherpeople',
            name='Joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherpeople',
            name='Order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherpeople',
            name='PerAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherpeople',
            name='PreAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherpeople',
            name='Retirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Degree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Degree_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Degree_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Degree_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='HSC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='HSC_Board',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='HSC_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='HSC_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Honours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Honours_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Honours_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Honours_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Masters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Masters_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Masters_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Masters_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='PerAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='PreAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='PreMasters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='PreMasters_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='PreMasters_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='PreMasters_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Retirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='SSC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='SSC_Board',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='SSC_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='SSC_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Degree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Degree_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Degree_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Degree_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='HSC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='HSC_Board',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='HSC_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='HSC_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Honours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Honours_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Honours_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Honours_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Masters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Masters_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Masters_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Masters_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='PerAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='PreAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='PreMasters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='PreMasters_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='PreMasters_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='PreMasters_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='SSC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='SSC_Board',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='SSC_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='SSC_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Degree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Degree_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Degree_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Degree_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='HSC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='HSC_Board',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='HSC_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='HSC_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Honours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Honours_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Honours_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Honours_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Masters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Masters_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Masters_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Masters_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='PerAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='PreAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='PreMasters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='PreMasters_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='PreMasters_U',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='PreMasters_Year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='SSC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='SSC_Board',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='SSC_Result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='SSC_Year',
            field=models.TextField(blank=True, null=True),
        ),
    ]
