# Generated by Django 5.0.2 on 2025-04-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0004_alter_exstaff_dob_alter_exstaff_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exstaff',
            name='Gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otherpeople',
            name='Gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
