# Generated by Django 4.1.13 on 2025-04-20 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kbm', '0004_remove_dept_users_remove_relatedimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='users',
            field=models.ManyToManyField(related_name='depts', to=settings.AUTH_USER_MODEL),
        ),
    ]
