# Generated by Django 4.1.13 on 2025-04-18 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0005_gallary_rename_caption_relatedimage_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedimage',
            name='Dept',
        ),
        migrations.AddField(
            model_name='gallary',
            name='Dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm.dept'),
        ),
    ]
