# Generated by Django 5.0.2 on 2025-04-08 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0005_alter_education_exteacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ExTeacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='kbm.exteacher'),
        ),
        migrations.AlterField(
            model_name='education',
            name='NonMpoStaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='kbm.nonmpostaff'),
        ),
        migrations.AlterField(
            model_name='education',
            name='Staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='kbm.staff'),
        ),
        migrations.AlterField(
            model_name='education',
            name='Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='kbm.teacher'),
        ),
        migrations.AlterField(
            model_name='education',
            name='TeacherHonours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='kbm.teacherhonours'),
        ),
    ]
