# Generated by Django 4.1.13 on 2025-04-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0005_dept_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='Dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbm.dept'),
        ),
    ]
