# Generated by Django 5.0.2 on 2025-04-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0005_alter_exstaff_gender_alter_exteacher_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonMpoStaff',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Img', models.ImageField(upload_to='images/personnel')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(blank=True, max_length=100, null=True)),
                ('Designation', models.CharField(max_length=100)),
                ('Dept', models.CharField(max_length=100)),
                ('FName', models.CharField(max_length=100)),
                ('MName', models.CharField(max_length=100)),
                ('Joining', models.DateField(blank=True, null=True)),
                ('Index', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=15)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('PreAddress', models.TextField(blank=True, null=True)),
                ('PerAddress', models.TextField(blank=True, null=True)),
                ('SSC', models.TextField(blank=True, null=True)),
                ('HSC', models.TextField(blank=True, null=True)),
                ('Degree', models.TextField(blank=True, null=True)),
                ('Honours', models.TextField(blank=True, null=True)),
                ('PreMasters', models.TextField(blank=True, null=True)),
                ('Masters', models.TextField(blank=True, null=True)),
                ('SSC_Year', models.TextField(blank=True, null=True)),
                ('HSC_Year', models.TextField(blank=True, null=True)),
                ('Degree_Year', models.TextField(blank=True, null=True)),
                ('Honours_Year', models.TextField(blank=True, null=True)),
                ('PreMasters_Year', models.TextField(blank=True, null=True)),
                ('Masters_Year', models.TextField(blank=True, null=True)),
                ('SSC_Result', models.TextField(blank=True, null=True)),
                ('HSC_Result', models.TextField(blank=True, null=True)),
                ('Degree_Result', models.TextField(blank=True, null=True)),
                ('Honours_Result', models.TextField(blank=True, null=True)),
                ('PreMasters_Result', models.TextField(blank=True, null=True)),
                ('Masters_Result', models.TextField(blank=True, null=True)),
                ('SSC_Board', models.TextField(blank=True, null=True)),
                ('HSC_Board', models.TextField(blank=True, null=True)),
                ('Degree_U', models.TextField(blank=True, null=True)),
                ('Honours_U', models.TextField(blank=True, null=True)),
                ('PreMasters_U', models.TextField(blank=True, null=True)),
                ('Masters_U', models.TextField(blank=True, null=True)),
                ('Experience', models.TextField(blank=True, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Order', models.IntegerField(blank=True, null=True)),
                ('Retirement', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
