# Generated by Django 5.0.2 on 2025-04-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0006_alter_education_exteacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exstaff',
            old_name='PerAddress2',
            new_name='PerAddress',
        ),
        migrations.RenameField(
            model_name='exstaff',
            old_name='PreAddress2',
            new_name='PreAddress',
        ),
        migrations.RenameField(
            model_name='exteacher',
            old_name='PerAddress2',
            new_name='PerAddress',
        ),
        migrations.RenameField(
            model_name='exteacher',
            old_name='PreAddress2',
            new_name='PreAddress',
        ),
        migrations.RenameField(
            model_name='nonmpostaff',
            old_name='PerAddress2',
            new_name='PerAddress',
        ),
        migrations.RenameField(
            model_name='nonmpostaff',
            old_name='PreAddress2',
            new_name='PreAddress',
        ),
        migrations.RenameField(
            model_name='otherpeople',
            old_name='PerAddress2',
            new_name='PerAddress',
        ),
        migrations.RenameField(
            model_name='otherpeople',
            old_name='PreAddress2',
            new_name='PreAddress',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='PerAddress2',
            new_name='PerAddress',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='PreAddress2',
            new_name='PreAddress',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='PerAddress2',
            new_name='PerAddress',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='PreAddress2',
            new_name='PreAddress',
        ),
        migrations.RenameField(
            model_name='teacherhonours',
            old_name='PerAddress2',
            new_name='PerAddress',
        ),
        migrations.RenameField(
            model_name='teacherhonours',
            old_name='PreAddress2',
            new_name='PreAddress',
        ),
    ]
