# Generated by Django 5.0.2 on 2025-04-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0006_nonmpostaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('HSC', 'HSC'), ('Degree', 'Degree'), ('Honours', 'Honours'), ('BBA', 'BBA'), ('BM', 'BM'), ('Open Uni.', 'Open Uni'), ('Agriculture', 'Agriculture'), ('All', 'All')], max_length=28, null=True)),
                ('text', models.TextField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, max_length=512, null=True)),
                ('img', models.ImageField(upload_to='images/notification')),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
