# Generated by Django 4.1.13 on 2025-04-18 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0007_remove_gallary_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedimage',
            name='Dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm.dept'),
        ),
    ]
