# Generated by Django 5.0.2 on 2025-04-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exstaff',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/personnel'),
        ),
        migrations.AlterField(
            model_name='exteacher',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/personnel'),
        ),
        migrations.AlterField(
            model_name='nonmpostaff',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/personnel'),
        ),
        migrations.AlterField(
            model_name='otherpeople',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/personnel'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/personnel'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/personnel'),
        ),
        migrations.AlterField(
            model_name='teacherhonours',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/personnel'),
        ),
    ]
