# Generated by Django 4.1.13 on 2025-04-20 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0009_remove_relatedimage_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedimage',
            name='Dept',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='kbm.dept'),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='Dept',
            field=models.ForeignKey(default=99, editable=False, on_delete=django.db.models.deletion.CASCADE, to='kbm.dept'),
        ),
    ]
