# Generated by Django 4.1.13 on 2025-04-20 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0010_relatedimage_dept_alter_gallary_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Departments',
        ),
        migrations.AddField(
            model_name='departments',
            name='Dept',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='kbm.dept'),
        ),
        migrations.AddField(
            model_name='post',
            name='Dept',
            field=models.ForeignKey(default=99, editable=False, on_delete=django.db.models.deletion.CASCADE, to='kbm.dept'),
        ),
    ]
