# Generated by Django 4.1.13 on 2025-04-20 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0011_remove_departments_name_remove_post_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='Dept',
            field=models.ForeignKey(default=99, editable=False, on_delete=django.db.models.deletion.CASCADE, to='kbm.dept'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
