# Generated by Django 4.1.13 on 2025-04-21 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kbm', '0012_alter_departments_dept_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='SubTitle',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Title',
        ),
        migrations.AlterField(
            model_name='departments',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PostDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('SubTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Comment', models.CharField(blank=True, max_length=255, null=True)),
                ('Dept', models.ForeignKey(default=99, editable=False, on_delete=django.db.models.deletion.CASCADE, to='kbm.dept')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
