# Generated by Django 4.1.13 on 2025-04-21 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0016_alter_postdetails_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetails',
            name='Dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbm.post'),
        ),
    ]
