# Generated by Django 4.1.13 on 2025-04-21 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0017_alter_postdetails_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetails',
            name='Post',
            field=models.ForeignKey(default=99, editable=False, on_delete=django.db.models.deletion.CASCADE, to='kbm.post'),
        ),
        migrations.AddField(
            model_name='relatedimage',
            name='Departments',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='kbm.departments'),
        ),
        migrations.AddField(
            model_name='relatedimage',
            name='Gallary',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='kbm.gallary'),
        ),
        migrations.AddField(
            model_name='relatedimage',
            name='PostDetails',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='kbm.postdetails'),
        ),
        migrations.AlterField(
            model_name='postdetails',
            name='Dept',
            field=models.ForeignKey(default=99, editable=False, on_delete=django.db.models.deletion.CASCADE, to='kbm.dept'),
        ),
    ]
