# Generated by Django 4.1.13 on 2025-04-21 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0018_postdetails_post_relatedimage_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetails',
            name='Post',
        ),
        migrations.AlterField(
            model_name='postdetails',
            name='Dept',
            field=models.ForeignKey(default=99, editable=False, on_delete=django.db.models.deletion.CASCADE, to='kbm.post'),
        ),
    ]
