# Generated by Django 4.1.13 on 2025-04-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0020_postdetails_post_alter_postdetails_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetails',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='postdetails',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='relatedimage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='relatedimage',
            name='object_id',
        ),
    ]
